### ISSUE TITLE
Deploy contract

### ISSUE THREAD

**Issue by Annammal** [Nikhil22/angular4-truffle-starter-dapp#15]
Hi, 
how to deploy contract with constructor? Is it possible guys

**Comment by Annammal** [comment]
createBlock(payManager, account): Observable<any> {
    let createInstance;
    return Observable.create(observer => {
      this.CreateBlock.new(payManager,{from: account})
        .then(instance => {
           createInstance = instance ;
          observer.next(createInstance);
          observer.complete();
        })
          return  createInstance.getfee.call()
            .then(value => {
              observer.next(value);
              observer.complete();
            })
         .catch(e => {
           console.log(e);
           observer.error(e);
          });
        });

  }

Is this right?

**Comment by Nikhil22** [comment]
I am not sure what you are trying to achieve.
