### ISSUE TITLE
MetaMask will not appear in the browser when the transaction needs to be approved

### ISSUE THREAD

**Issue by ronh73** [Nikhil22/angular4-truffle-starter-dapp#2]
MetaMask is injected into the browser after the AppComponent has been instantiated. The checkAndInstantiateWeb3 method that is executed within the constructor of AppComponent will always execute the else clause because of this. When sending metacoins to an address, MetaMask will never appear to approve the transaction, even though MetaMask is active in the Chrome browser. It is not picked up by the application.

**Comment by ronh73** [comment]
Using _typeof window['web3'] !== 'undefined'_ instead of _this.web3 !== 'undefined'_ 
and using new Web3(window['web3'].currentProvider) instead of new Web3(this.web3.currentProvider) did the trick. And moving the web3 instantiating from the constructor to the hook _ngAfterContentChecked_ method with a boolean to prevent from being executed only one time instead of many times.

**Comment by Nikhil22** [comment]
This is a good point, @ronh73 . The ngAfterViewInit lifecycle hook is a better use case for instantiating objects that require the view to be loaded first. I will make the changes.

**Comment by ronh73** [comment]
Thanks, that's good to hear. In my case the number of meta's is also not directly shown (could take about 10 seconds) and after a transaction the number of Meta's does not get updated. When typing the url in a new tab in Chrome, the number of Meta's shown will be correct.

By the way, I start testrpc with the -m flag. This is the same seed (aka mnemonic) that is generated by Metamask when creating an account.

**Comment by chrisfraser** [comment]
`ngAfterViewInit` is still to early in the page lifecycle. You have to hook the window.load event.  
![lifecycle](https://user-images.githubusercontent.com/929529/29161517-d3322e9a-7db6-11e7-9b6b-8b40bc1e0bb2.PNG)

**Comment by chrisfraser** [comment]
You can use a HostListener as follows instead of the constructor:
```javascript
@HostListener('window:load')
windowLoaded() {
  this.checkAndInstantiateWeb3();
  this.onReady();
}
```

**Comment by Nikhil22** [comment]
@chrisfraser Can you make a PR for this? I'll add you as a contributor to the README too

**Comment by chrisfraser** [comment]
@Nikhil22 Sure thing. I ran into another issue with the balance binding not updating. I will fix that on Tuesday and send something through.

**Comment by chrisfraser** [comment]
@Nikhil22 Check out https://github.com/Nikhil22/angular4-truffle-starter-dapp/pull/4

**Comment by Nikhil22** [comment]
@chrisfraser Thanks man, I'll review & merge you in.
